"use client";

import { ChevronDown, Crown, Network, Sparkles, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";
import type { AgentNode } from "@/lib/admin-types";
import { Skeleton, cents, money, surface, teamGmv, teamPlatform } from "./admin-dark-ui";
import { useAdminMobile } from "./admin-mobile-context";

export function AdminMobileTeam() {
  const { monthTree, loading } = useAdminMobile();
  const roots = monthTree?.root.children ?? [];
  const [filter, setFilter] = useState("all");
  const [open, setOpen] = useState<string | null>(null);
  const ranked = useMemo(() => [...roots].sort((a, b) => teamPlatform(b) - teamPlatform(a)), [roots]);
  const visible = filter === "all" ? ranked : ranked.filter((node) => node.id === filter);
  return <>
    <header className="mb-8"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#9FE870]">Network intelligence / 02</p><h1 className="mt-3 text-[30px] font-extrabold tracking-[-0.065em]">团队网络</h1><p className="mt-2 text-[12px] leading-5 text-[#8E9B8A]">一级代理与直属二级团队，本月贡献清晰可见。</p></header>
    <div className={surface + " flex items-center gap-3 p-4"}><span className="flex h-11 w-11 items-center justify-center rounded-full bg-[#9FE870] text-[#0A1408]"><Crown size={19} /></span><span className="flex-1"><span className="block text-[12px] font-bold">{monthTree?.root.displayName ?? "平台总控"}</span><span className="mt-1 block text-[10px] text-[#8E9B8A]">老板 · 全网根节点</span></span><span className="rounded-full border border-[#9FE870]/18 bg-[#9FE870]/10 px-2.5 py-1.5 font-mono text-[10px] text-[#9FE870]">LEVEL 0</span></div>
    <div className="mb-4 mt-9 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#758D70]">First generation</p><h2 className="mt-2 text-[18px] font-extrabold">一级代理</h2></div><span className="flex items-center gap-1.5 text-[10px] text-[#8E9B8A]"><Network size={13} />{roots.length} 位一级 · {roots.reduce((sum, node) => sum + node.children.length, 0)} 位二级</span></div>
    <div role="group" aria-label="按一级代理筛选" className="-mx-5 flex gap-2 overflow-x-auto px-5 pb-2 [scrollbar-width:none]"><button type="button" onClick={() => setFilter("all")} aria-pressed={filter === "all"} className={"h-9 shrink-0 rounded-full px-4 text-[11px] font-bold " + (filter === "all" ? "bg-[#9FE870] text-[#0A1408]" : "border border-white/[0.08] bg-[#141C13] text-[#8E9B8A]")}>全部</button>{roots.map((node) => <button key={node.id} type="button" onClick={() => { setFilter(node.id); setOpen(node.id); }} aria-pressed={filter === node.id} className={"h-9 shrink-0 rounded-full px-4 text-[11px] font-bold " + (filter === node.id ? "bg-[#9FE870] text-[#0A1408]" : "border border-white/[0.08] bg-[#141C13] text-[#8E9B8A]")}>{node.displayName}</button>)}</div>
    <div className="mt-4 space-y-3">{loading ? [0, 1, 2].map((index) => <div key={index} className={surface + " h-44 p-5"}><Skeleton className="h-full w-full" /></div>) : visible.map((node) => <TeamCard key={node.id} node={node} rank={ranked.findIndex((item) => item.id === node.id) + 1} open={open === node.id} onToggle={() => setOpen((old) => old === node.id ? null : node.id)} />)}</div>
    <p className="mt-6 flex items-center justify-center gap-1.5 text-[10px] text-[#74896F]"><Sparkles size={13} className="text-[#9FE870]" />排名按本月团队平台 30% 贡献计算</p>
  </>;
}

function TeamCard({ node, rank, open, onToggle }: { node: AgentNode; rank: number; open: boolean; onToggle: () => void }) {
  const mentor = node.children.reduce((sum, child) => sum + cents(child.mentorPaidUp), 0);
  return <section className={surface + " overflow-hidden"}><button type="button" onClick={onToggle} aria-expanded={open} aria-label={(open ? "收起" : "展开") + node.displayName + "的二级团队"} className="w-full p-5 text-left"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl border border-[#9FE870]/15 bg-[#263A21] text-[11px] font-extrabold text-[#C4E9B0]">{node.displayName.slice(0, 2)}</span><span className="min-w-0 flex-1"><span className="block truncate text-[13px] font-bold">{node.displayName}</span><span className="mt-1 block font-mono text-[10px] text-[#768971]">{node.referralCode}</span></span><span className="rounded-full border border-[#9FE870]/15 bg-[#9FE870]/10 px-2.5 py-1 font-mono text-[10px] font-bold text-[#9FE870]">#{rank}</span><ChevronDown size={16} className={"text-[#93A68B] transition-transform " + (open ? "rotate-180" : "")} /></div><div className="mt-5 grid grid-cols-3 gap-2"><div><p className="text-[9px] text-[#80917B]">本月团队 GMV</p><p className="mt-1.5 truncate font-mono text-[12px] font-bold">¥{money(teamGmv(node))}</p></div><div><p className="text-[9px] text-[#80917B]">平台 30%</p><p className="mt-1.5 truncate font-mono text-[12px] font-bold text-[#9FE870]">¥{money(teamPlatform(node))}</p></div><div><p className="text-[9px] text-[#80917B]">直属二级</p><p className="mt-1.5 font-mono text-[12px] font-bold">{node.teamSize} 人</p></div></div></button>{open && <div className="border-t border-white/[0.06] px-5 pb-5 pt-4"><p className="mb-3 text-[10px] text-[#869A80]">二级直属团队 · 仅向当前导师流转 21%</p>{node.children.length ? <div className="ml-2 space-y-2 border-l border-[#385333] pl-4">{node.children.map((child) => <div key={child.id} className="relative flex items-center gap-3 rounded-2xl border border-white/[0.05] bg-[#101810] px-3 py-3"><span aria-hidden="true" className="absolute -left-4 top-1/2 h-px w-4 bg-[#385333]" /><span className="flex h-8 w-8 items-center justify-center rounded-full border border-white/[0.06] bg-white/[0.06] text-[10px] font-bold text-[#C9E6B9]">{child.displayName.slice(0, 2)}</span><span className="min-w-0 flex-1"><span className="block truncate text-[11px] font-bold">{child.displayName}</span><span className="mt-1 block text-[9px] text-[#82947C]">{child.ownOrderCount} 笔 · GMV ¥{child.ownGmv}</span></span><span className="text-right"><span className="block text-[9px] text-[#7F9479]">导师 21%</span><span className="mt-1 block font-mono text-[11px] font-bold text-[#9FE870]">+¥{child.mentorPaidUp}</span></span></div>)}</div> : <p className="rounded-2xl border border-white/[0.05] bg-[#101810] px-4 py-5 text-center text-[11px] text-[#7C8E77]">暂无直属二级代理</p>}<p className="mt-4 text-right text-[10px] text-[#879B80]">团队导师分润 <span className="ml-1 font-mono font-bold text-[#9FE870]">¥{money(mentor)}</span></p></div>}</section>;
}
