"use client";

import Link from "next/link";
import { Activity, ArrowUpRight, ChevronDown, ChevronLeft, ChevronRight, Command, Crown,
  Layers3, Network, Search, Sparkles, TrendingDown, TrendingUp, UsersRound, WalletCards, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { adminGet } from "@/lib/admin-api";
import { demoAdminOverview, demoAdminOverviewMonth, demoAdminOverviewPreviousMonth,
  demoAuditItems, demoTeamTree, demoTeamTreeMonth } from "@/lib/admin-demo-data";
import type { AdminOverview, AgentNode, AuditPage, TeamTree } from "@/lib/admin-types";
import { AuditFlowCard, Skeleton, cents, findAgent, money, surface, teamGmv, teamPlatform } from "./admin-dark-ui";

type Period = "all" | "month";
const PAGE_SIZE = 5;
function demoAudit(period: Period, page: number, query: string): AuditPage {
  const q = query.toLocaleLowerCase();
  const source = demoAuditItems.filter((item) => (period === "all" || item.createdAt.startsWith("2026-09")) &&
    (!q || item.orderNo.toLocaleLowerCase().includes(q) || item.promoter.displayName.toLocaleLowerCase().includes(q)));
  return { page, pageSize: PAGE_SIZE, total: source.length, totalPages: Math.ceil(source.length / PAGE_SIZE),
    items: source.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE) };
}
function matches(node: AgentNode, query: string) {
  const q = query.toLocaleLowerCase();
  return node.displayName.toLocaleLowerCase().includes(q) || (node.referralCode ?? "").toLocaleLowerCase().includes(q);
}
function Metric({ label, value, detail, icon: Icon, loading }: { label: string; value: string; detail: string; icon: typeof Activity; loading: boolean }) {
  return <article className={surface + " flex min-h-[236px] flex-col p-6 transition-colors hover:bg-[#182217]"}>
    <div className="flex items-start justify-between gap-2"><span className="text-[11px] font-medium text-[#8E9B8A]">{label}</span><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl border border-white/[0.06] bg-white/[0.05] text-[#A9CB9C]"><Icon size={18} strokeWidth={1.5} /></span></div>
    <div className="mt-auto">{loading ? <Skeleton className="h-9 w-[88%]" /> : <p className="overflow-hidden text-ellipsis whitespace-nowrap font-mono text-[clamp(19px,1.7vw,27px)] font-bold tracking-[-0.075em] text-[#F4F5F0]">{value}</p>}<p className="mt-3 text-[10px] leading-5 text-[#6F806C]">{detail}</p></div>
  </article>;
}
function TeamRoot({ node, open, activeId, onToggle, onSelect, query, period }: { node: AgentNode; open: boolean; activeId: string | null; onToggle: () => void; onSelect: (id: string) => void; query: string; period: Period }) {
  const visibleChildren = query && !matches(node, query) ? node.children.filter((child) => matches(child, query)) : node.children;
  const mentor = node.children.reduce((sum, child) => sum + cents(child.mentorPaidUp), 0);
  return <div className={surface + " overflow-hidden transition-colors hover:bg-[#182217]"}>
    <div className="flex items-center gap-4 p-5"><button type="button" onClick={() => onSelect(node.id)} className="flex min-w-[174px] flex-[1.3] items-center gap-3 rounded-xl text-left focus-visible:outline-2 focus-visible:outline-[#9FE870]"><span className={"flex h-12 w-12 shrink-0 items-center justify-center rounded-[17px] text-[12px] font-extrabold " + (activeId === node.id ? "bg-[#9FE870] text-[#0A1408]" : "border border-white/[0.08] bg-[#263623] text-[#B5DB9F]")}>{node.displayName.slice(0, 2)}</span><span className="min-w-0"><span className="block truncate text-[13px] font-bold text-[#F4F5F0]">{node.displayName}</span><span className="mt-1 block truncate font-mono text-[10px] text-[#748570]">{node.referralCode} · 一级代理</span></span></button><div className="min-w-[110px] flex-1"><p className="text-[10px] text-[#788875]">{period === "month" ? "本月团队 GMV" : "团队成交 GMV"}</p><p className="mt-1.5 truncate font-mono text-[13px] font-semibold text-[#DDE9D7]">¥{money(teamGmv(node))}</p></div><div className="min-w-[80px] flex-[.55]"><p className="text-[10px] text-[#788875]">直属下线</p><p className="mt-1.5 font-mono text-[13px] font-semibold text-[#DDE9D7]">{node.teamSize} 人</p></div><div className="min-w-[123px] flex-1"><p className="text-[10px] text-[#788875]">平台 30% 贡献</p><p className="mt-1.5 truncate font-mono text-[13px] font-semibold text-[#9FE870]">¥{money(teamPlatform(node))}</p></div><button type="button" onClick={onToggle} disabled={!node.children.length} aria-expanded={open} aria-label={(open ? "收起" : "展开") + node.displayName + "团队"} className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-white/[0.08] bg-white/[0.05] text-[#B5C9AA] disabled:opacity-30"><ChevronDown size={17} className={open ? "rotate-180 transition-transform" : "transition-transform"} /></button></div>
    {open && visibleChildren.length > 0 && <div className="border-t border-white/[0.06] px-5 pb-5 pt-4"><p className="mb-4 pl-3 text-[10px] text-[#7F9279]">二级直属团队 <span className="mx-1 text-[#496045]">/</span> 利润池 21% 向直属导师分润</p><div className="ml-6 space-y-2.5 border-l border-[#385333] pl-4">{visibleChildren.map((child) => <button key={child.id} type="button" onClick={() => onSelect(child.id)} className={"relative flex w-full items-center gap-3 rounded-[17px] border px-4 py-3.5 text-left transition-colors " + (activeId === child.id ? "border-[#9FE870]/25 bg-[#21351B]" : "border-white/[0.05] bg-[#101810] hover:bg-[#1B2918]")}><span aria-hidden="true" className="absolute -left-4 top-1/2 h-px w-4 bg-[#385333]" /><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-white/[0.08] bg-[#253421] text-[10px] font-bold text-[#C6EAB0]">{child.displayName.slice(0, 2)}</span><span className="min-w-0 flex-1"><span className="block truncate text-[12px] font-bold text-[#F4F5F0]">{child.displayName} <span className="font-mono text-[9px] font-normal text-[#70816D]">#{child.referralCode}</span></span><span className="mt-1 block truncate text-[10px] text-[#7C8E77]">{child.ownOrderCount} 笔出单 · GMV ¥{child.ownGmv}</span></span><span className="shrink-0 text-right"><span className="block text-[9px] text-[#748771]">导师 21%</span><span className="mt-1 block font-mono text-[12px] font-bold text-[#9FE870]">+¥{child.mentorPaidUp}</span></span></button>)}</div><p className="mt-4 text-right text-[10px] text-[#80927A]">累计导师分润 <span className="ml-1 font-mono font-bold text-[#9FE870]">¥{money(mentor)}</span></p></div>}
  </div>;
}
function Inspector({ selected, parent }: { selected: AgentNode | null; parent: AgentNode | null }) {
  const received = selected?.children.reduce((sum, child) => sum + cents(child.mentorPaidUp), 0) ?? 0;
  return <aside className="sticky top-[118px] self-start rounded-[28px] border border-[#9FE870]/12 bg-[#1A2917] p-6"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#8EA887]">Agent focus</span><Sparkles size={17} className="text-[#9FE870]" /></div>{selected ? <><div className="mt-7 flex items-center gap-3"><span className="flex h-14 w-14 items-center justify-center rounded-[18px] bg-[#9FE870] text-[15px] font-extrabold text-[#0A1408]">{selected.displayName.slice(0, 2)}</span><div><h3 className="text-[21px] font-bold tracking-[-0.05em] text-[#F4F5F0]">{selected.displayName}</h3><p className="mt-1 text-[10px] text-[#8A9D84]">{parent ? "二级代理 · 导师 " + parent.displayName : "一级代理 · 平台直属"}</p></div></div><p className="mt-5 inline-flex rounded-full border border-white/[0.08] bg-white/[0.04] px-3 py-1.5 font-mono text-[10px] text-[#BAD7AD]">{selected.referralCode}</p><div className="mt-7 rounded-[20px] border border-white/[0.06] bg-[#111B10] p-5"><p className="text-[11px] text-[#84977C]">钱包可用余额</p><p className="mt-3 font-mono text-[29px] font-bold tracking-[-0.075em] text-[#F4F5F0]">¥{selected.balance}</p></div><div className="mt-5 grid grid-cols-2 gap-4">{[["自身成交 GMV", selected.ownGmv], ["历史总收益", selected.totalEarned], ["直属团队", selected.teamSize + " 人"], ["平台贡献", selected.platformContribution]].map(([label, value]) => <div key={label}><p className="text-[10px] text-[#82947B]">{label}</p><p className="mt-2 truncate font-mono text-[13px] font-semibold text-[#EDF4E9]">{label === "直属团队" ? value : "¥" + value}</p></div>)}</div><div className="mt-7 flex items-center justify-between gap-2 rounded-2xl bg-[#9FE870]/10 px-4 py-3 text-[10px] text-[#BADCA7]"><span>{parent ? "向直属导师流转 21%" : "直属团队导师分润"}</span><span className="font-mono font-bold text-[#9FE870]">¥{parent ? selected.mentorPaidUp : money(received)}</span></div></> : <p className="mt-8 text-[12px] leading-6 text-[#8EA887]">选择代理，查看团队与钱包数据。</p>}</aside>;
}

export function AdminDashboard({ demo = false }: { demo?: boolean }) {
  const [period, setPeriod] = useState<Period>("all"), [query, setQuery] = useState(""), [search, setSearch] = useState("");
  const [page, setPage] = useState(1), [revision, setRevision] = useState(0);
  const [overview, setOverview] = useState<AdminOverview | null>(demo ? demoAdminOverview : null);
  const [month, setMonth] = useState<AdminOverview | null>(demo ? demoAdminOverviewMonth : null);
  const [previousMonth, setPreviousMonth] = useState<AdminOverview | null>(demo ? demoAdminOverviewPreviousMonth : null);
  const [tree, setTree] = useState<TeamTree | null>(demo ? demoTeamTree : null);
  const [audit, setAudit] = useState<AuditPage | null>(demo ? demoAudit("all", 1, "") : null);
  const [selectedId, setSelectedId] = useState<string | null>(demo ? demoTeamTree.root.children[0]?.id ?? null : null);
  const [openRoots, setOpenRoots] = useState<Set<string>>(new Set(demo ? [demoTeamTree.root.children[0]?.id ?? ""] : []));
  const [loadingOverview, setLoadingOverview] = useState(!demo), [loadingTree, setLoadingTree] = useState(!demo), [loadingAudit, setLoadingAudit] = useState(!demo);
  const [error, setError] = useState(""); const searchRef = useRef<HTMLInputElement>(null);
  useEffect(() => { const timer = window.setTimeout(() => { setSearch(query.trim()); setPage(1); }, 260); return () => window.clearTimeout(timer); }, [query]);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); searchRef.current?.focus(); } if (event.key === "Escape" && document.activeElement === searchRef.current) { setQuery(""); searchRef.current?.blur(); } }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  useEffect(() => { if (demo) return; const timer = window.setInterval(() => setRevision((old) => old + 1), 60_000); return () => window.clearInterval(timer); }, [demo]);
  useEffect(() => {
    if (demo) { setOverview(period === "month" ? demoAdminOverviewMonth : demoAdminOverview); setTree(period === "month" ? demoTeamTreeMonth : demoTeamTree); return; }
    const controller = new AbortController(); setLoadingOverview(true); setLoadingTree(true);
    adminGet<AdminOverview>("/api/admin/overview?period=" + period, controller.signal).then(setOverview).catch(() => { if (!controller.signal.aborted) setError("资金数据暂时不可用，请检查管理员会话。"); }).finally(() => { if (!controller.signal.aborted) setLoadingOverview(false); });
    adminGet<TeamTree>("/api/admin/team-tree?period=" + period, controller.signal).then((result) => { setTree(result); setSelectedId((old) => old && findAgent(result.root.children, old) ? old : result.root.children[0]?.id ?? null); }).catch(() => { if (!controller.signal.aborted) setError("团队数据暂时不可用，请检查管理员会话。"); }).finally(() => { if (!controller.signal.aborted) setLoadingTree(false); });
    return () => controller.abort();
  }, [demo, period, revision]);
  useEffect(() => { if (demo) return; const controller = new AbortController(); Promise.all([adminGet<AdminOverview>("/api/admin/overview?period=month", controller.signal), adminGet<AdminOverview>("/api/admin/overview?period=previous_month", controller.signal)]).then(([current, previous]) => { setMonth(current); setPreviousMonth(previous); }).catch(() => {}); return () => controller.abort(); }, [demo, revision]);
  useEffect(() => { if (demo) { setAudit(demoAudit(period, page, search)); return; } const controller = new AbortController(); setLoadingAudit(true); const params = new URLSearchParams({ period, page: String(page), pageSize: String(PAGE_SIZE) }); if (search) params.set("q", search); adminGet<AuditPage>("/api/admin/commission-audit?" + params, controller.signal).then(setAudit).catch(() => { if (!controller.signal.aborted) setError("审计流水暂时不可用，请检查管理员会话。"); }).finally(() => { if (!controller.signal.aborted) setLoadingAudit(false); }); return () => controller.abort(); }, [demo, period, page, search, revision]);
  const roots = tree?.root.children ?? [];
  const visibleRoots = useMemo(() => roots.filter((node) => !search || matches(node, search) || node.children.some((child) => matches(child, search))), [roots, search]);
  const selected = selectedId ? findAgent(roots, selectedId) : null;
  const parent = selected ? roots.find((node) => node.children.some((child) => child.id === selected.id)) ?? null : null;
  const previous = cents(previousMonth?.platformTotalRevenue ?? "0");
  const trend = previous ? Math.round(((cents(month?.platformTotalRevenue ?? "0") / previous) - 1) * 1000) / 10 : null;
  const ready = Boolean(overview && tree && audit) && !error;
  function changePeriod(next: Period) { setPeriod(next); setPage(1); setError(""); }
  function toggleRoot(id: string) { setOpenRoots((old) => { const next = new Set(old); if (next.has(id)) next.delete(id); else next.add(id); return next; }); }

  return <div className="min-h-screen bg-[#0B0F0B] font-sans text-[#F4F5F0] antialiased"><div className="mx-auto max-w-[1600px] px-6 pb-20 pt-6 xl:px-9 2xl:px-12">
    <header className="sticky top-5 z-30 flex min-h-[72px] items-center justify-between gap-5 rounded-full border border-white/[0.08] bg-[#0D140C]/80 px-5 shadow-[0_18px_55px_-25px_rgba(0,0,0,.7)] backdrop-blur-md xl:px-7"><div className="flex shrink-0 items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full border border-[#9FE870]/15 bg-[#1C3019] text-[#9FE870]"><Layers3 size={19} strokeWidth={1.7} /></span><span><span className="block text-[11px] font-extrabold tracking-[0.13em]">PLATFORM CONSOLE</span><span className="mt-1 flex items-center gap-1.5 text-[10px] text-[#8E9B8A]"><span className={"h-1.5 w-1.5 rounded-full " + (ready ? "animate-pulse bg-[#9FE870]" : "bg-[#70816D]")} />{ready ? "系统运行正常" : error ? "部分数据待重试" : "正在连接"}</span></span></div><div className="flex min-w-0 items-center gap-3"><label className="hidden h-10 w-[260px] items-center gap-2 rounded-full border border-white/[0.06] bg-white/[0.04] px-4 text-[#81917D] lg:flex"><Search size={15} /><input ref={searchRef} value={query} onChange={(event) => setQuery(event.target.value)} maxLength={80} aria-label="搜索订单或代理" placeholder="搜索订单或代理" className="min-w-0 flex-1 bg-transparent text-[12px] text-[#F4F5F0] outline-none placeholder:text-[#71806D]" />{query ? <button type="button" onClick={() => setQuery("")} aria-label="清空搜索"><X size={14} /></button> : <kbd className="flex items-center gap-0.5 rounded-md border border-white/[0.06] px-1.5 py-1 font-mono text-[10px]"><Command size={10} />K</kbd>}</label><div role="group" aria-label="统计周期" className="flex h-10 items-center rounded-full border border-white/[0.06] bg-white/[0.04] p-1"><button type="button" aria-pressed={period === "month"} onClick={() => changePeriod("month")} className={"h-8 rounded-full px-3.5 text-[11px] font-bold " + (period === "month" ? "bg-[#9FE870] text-[#0A1408]" : "text-[#8E9B8A]")}>本月</button><button type="button" aria-pressed={period === "all"} onClick={() => changePeriod("all")} className={"h-8 rounded-full px-3.5 text-[11px] font-bold " + (period === "all" ? "bg-[#9FE870] text-[#0A1408]" : "text-[#8E9B8A]")}>全周期</button></div><Link href="/admin/mobile/" className="hidden h-10 items-center rounded-full border border-white/[0.08] px-4 text-[11px] font-semibold text-[#B8CBB0] hover:border-[#9FE870]/30 xl:flex">移动总控 <ArrowUpRight size={13} className="ml-1" /></Link><span className="flex h-10 w-10 items-center justify-center rounded-full border border-[#9FE870]/15 bg-[#263A21] text-[12px] font-bold text-[#C6E9B2]">老板</span></div></header>
    <main className="pt-11"><div className="mb-9 flex items-end justify-between gap-5"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#9FE870]">Capital intelligence</p><h1 className="mt-3 text-[38px] font-extrabold tracking-[-0.07em] xl:text-[44px]">让每一笔资金，都有迹可循<span className="text-[#9FE870]">.</span></h1><p className="mt-3 text-[12px] text-[#8E9B8A]">全网成交、二级代理与三方分润，在同一视野里清晰展开。</p></div><span className="rounded-full border border-white/[0.08] bg-[#141C13] px-3 py-2 text-[10px] text-[#9DAC98]">{demo ? "公开演示 · 虚构数据" : "仅超级管理员可查看"} · {period === "month" ? "本月 UTC" : "全周期"}</span></div>
      {error && <button type="button" onClick={() => { setError(""); setRevision((old) => old + 1); }} role="alert" className={surface + " mb-6 flex w-full justify-between px-5 py-4 text-left text-[12px] text-[#C9D6C3]"}><span>{error}</span><span className="text-[#9FE870]">点击重试 →</span></button>}
      <section aria-label="全盘资金中枢" className="grid gap-5 xl:grid-cols-[minmax(0,5fr)_minmax(0,7fr)]"><article className="relative flex min-h-[255px] flex-col overflow-hidden rounded-[30px] border border-[#9FE870]/12 bg-gradient-to-br from-[#162613] to-[#121E10] p-8 shadow-[0_22px_60px_-30px_rgba(0,0,0,.8)]"><span aria-hidden="true" className="absolute -right-12 -top-24 h-72 w-72 rounded-full border border-white/[0.06]" /><span aria-hidden="true" className="absolute right-7 top-3 h-40 w-40 rounded-full border border-white/[0.04]" /><div className="relative flex items-start justify-between"><div><p className="text-[12px] font-semibold text-[#E2EBDD]">平台累计净收益</p><p className="mt-2 text-[10px] text-[#93A98B]">订单利润池固定留存 30%</p></div><span className="flex h-11 w-11 items-center justify-center rounded-2xl border border-white/[0.08] bg-white/[0.06] text-[#9FE870]"><Crown size={20} strokeWidth={1.5} /></span></div><div className="relative mt-auto">{loadingOverview ? <Skeleton className="h-12 w-3/4" /> : <p className="whitespace-nowrap font-mono text-[clamp(32px,3vw,48px)] font-bold tracking-[-0.085em] text-[#F4F5F0] [text-shadow:0_0_30px_rgba(255,255,255,.11)]"><span className="mr-1 text-[.65em] text-[#AABCA2]">¥</span>{overview?.platformTotalRevenue ?? "—"}</p>}<div className={"mt-5 flex w-max items-center gap-1.5 rounded-full px-3 py-1.5 text-[10px] font-extrabold " + (trend !== null && trend < 0 ? "border border-white/[0.08] bg-white/[0.08] text-[#B7C5B0]" : "bg-[#9FE870] text-[#0A1408]")}>{trend !== null && trend < 0 ? <TrendingDown size={13} /> : <TrendingUp size={13} />}{trend === null ? "30% 固定利润留存" : `本月环比 ${trend > 0 ? "+" : ""}${trend.toFixed(1)}%`}</div></div></article><div className="grid grid-cols-3 gap-5"><Metric icon={Activity} label="全网 GMV 总成交" value={"¥" + (overview?.totalGmv ?? "—")} detail={(overview?.paidOrderCount ?? 0).toLocaleString() + " 笔已支付订单"} loading={loadingOverview} /><Metric icon={WalletCards} label="代理已分润奖金池" value={"¥" + (overview?.agentCommissionPool ?? "—")} detail="利润池 70% · 出单与导师" loading={loadingOverview} /><Metric icon={UsersRound} label="网络合伙人总数" value={String(overview?.agentCount ?? 0).padStart(2, "0")} detail={roots.length + " 位一级 · " + roots.reduce((sum, node) => sum + node.children.length, 0) + " 位二级"} loading={loadingOverview || loadingTree} /></div></section>
      <section className="mt-14" aria-labelledby="tree-heading"><div className="mb-6 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#76906C]">Network / 01</p><h2 id="tree-heading" className="mt-2 text-[25px] font-extrabold tracking-[-0.06em]">代理裂变拓扑</h2><p className="mt-2 text-[12px] text-[#8E9B8A]">平台主管 → 一级代理 → 二级团队，严格一层导师分润。</p></div><span className="inline-flex items-center gap-1.5 rounded-full border border-[#9FE870]/20 bg-[#9FE870]/10 px-3 py-2 text-[10px] font-bold text-[#9FE870]"><Network size={14} />二级结构</span></div><div className="grid gap-5 xl:grid-cols-[minmax(0,1.9fr)_minmax(320px,.9fr)]"><div className="space-y-3.5"><div className="flex items-center gap-3 rounded-[22px] border border-[#9FE870]/12 bg-[#172516] px-5 py-4"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#9FE870] text-[#0A1408]"><Crown size={16} /></span><span><span className="block text-[12px] font-bold">{tree?.root.displayName ?? "平台总控"}</span><span className="mt-1 block text-[10px] text-[#8E9B8A]">根节点 · {roots.length} 位直属一级代理</span></span><span className="ml-auto rounded-full border border-white/[0.08] px-2.5 py-1 font-mono text-[10px] text-[#97B58A]">LEVEL 0</span></div>{loadingTree ? [0, 1, 2].map((index) => <div key={index} className={surface + " h-24 p-5"}><Skeleton className="h-12 w-full" /></div>) : visibleRoots.length ? visibleRoots.map((node) => <TeamRoot key={node.id} node={node} open={openRoots.has(node.id) || Boolean(search)} activeId={selectedId} onToggle={() => toggleRoot(node.id)} onSelect={setSelectedId} query={search} period={period} />) : <p className={surface + " px-6 py-12 text-center text-[12px] text-[#8E9B8A]"}>没有匹配的代理。</p>}</div><Inspector selected={selected} parent={parent} /></div></section>
      <section className="mt-14" aria-labelledby="audit-heading"><div className="mb-6 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#76906C]">Capital flow / 02</p><h2 id="audit-heading" className="mt-2 text-[25px] font-extrabold tracking-[-0.06em]">全网分润审计</h2><p className="mt-2 text-[12px] text-[#8E9B8A]">每笔订单清晰拆解利润池、平台留存、出单人和直属导师。</p></div><span className="rounded-full border border-white/[0.08] bg-[#141C13] px-3 py-2 font-mono text-[10px] text-[#9EB097]">{audit?.total ?? 0} ORDERS</span></div><div className="space-y-3.5">{loadingAudit ? [0, 1, 2].map((index) => <div key={index} className={surface + " h-[160px] p-5"}><Skeleton className="h-full w-full" /></div>) : audit?.items.length ? audit.items.map((item) => <AuditFlowCard key={item.id} item={item} />) : <p className={surface + " px-6 py-14 text-center text-[12px] text-[#8E9B8A]"}>当前条件下暂无订单。</p>}</div><div className="mt-5 flex items-center justify-between"><p className="text-[10px] text-[#73836F]">{demo ? "精选演示订单" : "金额来自实际结算流水"} · UTC 时间</p><div className="flex items-center gap-3"><span className="font-mono text-[10px] text-[#8E9B8A]">{page} / {Math.max(audit?.totalPages ?? 1, 1)}</span><button type="button" onClick={() => setPage((old) => Math.max(1, old - 1))} disabled={page <= 1 || loadingAudit} aria-label="上一页" className="flex h-9 w-9 items-center justify-center rounded-full border border-white/[0.08] bg-[#141C13] text-[#C2D4B8] disabled:opacity-30"><ChevronLeft size={16} /></button><button type="button" onClick={() => setPage((old) => old + 1)} disabled={loadingAudit || !audit || page >= audit.totalPages} aria-label="下一页" className="flex h-9 w-9 items-center justify-center rounded-full border border-white/[0.08] bg-[#141C13] text-[#C2D4B8] disabled:opacity-30"><ChevronRight size={16} /></button></div></div></section>
      <footer className="mt-16 flex items-center justify-between border-t border-white/[0.07] pt-5 text-[10px] text-[#61745D]"><span>PLATFORM CONSOLE · 严格二级分润</span><span className="font-mono">30% PLATFORM / 70% AGENTS</span></footer>
    </main></div></div>;
}
